---
- name: Deploy exersice applications
  hosts: applicationservers
  roles:
    - { role: nodejs, tags: nodejs }
    - { role: daemon, tags: daemon }
    - { role: getcounter-app, tags: getcounter-app }
