---
- name: Deploy exersice applications
  hosts: applicationservers
  roles:
    - { role: nodejs, tags: nodejs }
    - { role: daemon, tags: daemon }
    - { role: pandaimg-app, tags: pandaimg-app }
